language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install build-essential 
  - pip install coveralls
script:
  - ./install.sh --noask
after_success:
  - rm $(find -name '*.gcno' | grep -v '.libs')
  - coveralls
  - coveralls -r $(pwd)/ibrdtn --exclude ibrcommon/tests --exclude ibrdtn/tests --exclude daemon/tests
