## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
  obj = bld.create_ns3_program('rescue-simple-ex', ['core', 'mobility', 'propagation', 'applications', 'rescue'])
  obj.source = 'rescue-simple-ex.cc'

  obj = bld.create_ns3_program('rescue-linear-multihop-ex', ['core', 'propagation', 'applications', 'aodv', 'mobility', 'rescue'])
  obj.source = 'rescue-linear-multihop-ex.cc'

